"""2023 재정학 enrichment"""
import json
from pathlib import Path

ENRICHMENT = [
    {"number":1,"topicId":"micro_welfare","keywords":["파레토효율","파레토개선","한계대체율","효용가능경계"],"coreStatement":"파레토개선: 최소 한 명의 효용↑, 누구의 효용도 ↓ 아님. 파레토효율: 더 이상 파레토개선 불가능한 상태.","answer":4,"basicExplanation":"파레토효율 달성 조건: MRS_A=MRS_B(교환), MRTS_X=MRTS_Y(생산), MRS=MRT(종합). 경쟁균형은 파레토효율적(제1후생정리).","detailedExplanation":"【파레토 효율성 3조건】\n교환효율: MRS_A=MRS_B\n생산효율: MRTS_X=MRTS_Y\n종합효율: MRS=MRT\n파레토개선: 한 명 이상 better off, 누구도 worse off 아님\n파레토효율: 파레토개선 불가능한 상태","difficulty":1},
    {"number":2,"topicId":"micro_welfare","keywords":["에지워스박스","계약곡선","초기부존","경쟁균형","코어"],"coreStatement":"에지워스 박스에서 계약곡선은 MRS_A=MRS_B인 점들의 집합이며, 경쟁균형은 계약곡선 위에 있다.","answer":3,"basicExplanation":"에지워스 박스: 2인 2재화 순수교환경제. 계약곡선: 파레토효율적 배분의 집합. 코어: 두 사람 모두 초기부존보다 나은 계약곡선 부분.","detailedExplanation":"【에지워스 박스 분석】\n크기: 총재화량(X, Y)으로 결정\n무차별곡선 접점=MRS_A=MRS_B=계약곡선\n코어: 초기부존의 무차별곡선 사이 계약곡선 부분\n경쟁균형: 예산선과 무차별곡선 접점+시장청산","difficulty":2},
    {"number":3,"topicId":"micro_consumer","keywords":["소비자이론","소득효과","대체효과","슬러츠키","기펜재"],"coreStatement":"가격↓ 시 대체효과는 항상 수요↑, 소득효과는 정상재↑·열등재↓. 기펜재: 소득효과가 대체효과 압도→가격↓수요↓.","answer":2,"basicExplanation":"슬러츠키 분해: 가격효과=대체효과+소득효과. 대체효과 항상 음(가격↓→수요↑). 기펜재: 열등재+소득효과>대체효과.","detailedExplanation":"【가격효과 분해】\n대체효과: 가격비 변화→상대적으로 싸진 재화 더 소비(항상 음)\n소득효과: 실질소득 변화→정상재(수요↑), 열등재(수요↓)\n\n정상재: 대체+소득 같은 방향→수요↑ 확실\n열등재: 대체(↑)+소득(↓) 반대→순효과에 따라\n기펜재: 열등재+소득효과 압도→수요법칙 위배","difficulty":2},
    {"number":4,"topicId":"micro_demand_supply","keywords":["수요공급","균형가격","수요이동","공급이동","탄력성"],"coreStatement":"수요 증가→균형가격↑·균형거래량↑. 공급 증가→균형가격↓·균형거래량↑. 동시 변화 시 방향은 상대적 크기에 의존.","answer":1,"basicExplanation":"수요곡선 우이동: D↑→P↑, Q↑. 공급곡선 우이동: S↑→P↓, Q↑. 수요·공급 동시 증가: Q↑확실, P 불확실.","detailedExplanation":"【수요공급 변화 분석】\n수요만 증가: P↑, Q↑\n공급만 증가: P↓, Q↑\n수요+공급 동시 증가: Q↑ 확실, P는 상대적 크기에 의존\n수요↑+공급↓: P↑ 확실, Q 불확실","difficulty":1},
    {"number":5,"topicId":"micro_elasticity","keywords":["수요탄력성","가격탄력성","소득탄력성","교차탄력성","탄력성결정요인"],"coreStatement":"가격탄력성 결정요인: 대체재 수, 필수vs사치, 지출비중, 기간. 장기>단기 탄력성.","answer":3,"basicExplanation":"대체재 많을수록 탄력적. 사치재>필수재 탄력적. 소비지출 비중 클수록 탄력적. 장기>단기(조정시간).","detailedExplanation":"【탄력성 결정요인】\n①대체재 수: 많을수록 |Ed|↑\n②필수재vs사치재: 사치재가 더 탄력적\n③지출비중: 클수록 탄력적\n④기간: 장기>단기(조정시간 있을수록)\n⑤재화정의 범위: 좁을수록 탄력적","difficulty":1},
    {"number":6,"topicId":"micro_consumer","keywords":["효용극대화","한계효용","무차별곡선","예산제약","MRS"],"coreStatement":"효용극대화: MRS=P_x/P_y, 즉 MU_x/P_x=MU_y/P_y (한계효용균등법칙). 예산선과 무차별곡선의 접점.","answer":4,"basicExplanation":"효용극대화 조건: MRS_xy=P_x/P_y. 한계효용균등법칙: MU_x/P_x=MU_y/P_y=λ(한계효용의 화폐가치).","detailedExplanation":"【효용극대화】\n라그랑주: max U(x,y) s.t. P_x·x+P_y·y=M\nFOC: MU_x/P_x = MU_y/P_y = λ\n기하학적: 무차별곡선과 예산선의 접점\nMRS = MU_x/MU_y = P_x/P_y","difficulty":1},
    {"number":7,"topicId":"micro_producer","keywords":["생산자이론","등량곡선","한계기술대체율","규모수익","비용함수"],"coreStatement":"비용최소화: MRTS=w/r (등량곡선과 등비용선 접점). 규모수익: 체증(α+β>1), 불변(=1), 체감(<1).","answer":2,"basicExplanation":"MRTS_LK=MP_L/MP_K=w/r. 비용최소화: 주어진 산출량을 최소비용으로 생산. 규모수익: 투입 n배→산출 n배 이상/이하.","detailedExplanation":"【비용최소화】\nmin wL+rK s.t. f(L,K)=Q\nFOC: MP_L/w = MP_K/r → MRTS=w/r\n\n【규모수익(Cobb-Douglas: Q=AL^α K^β)】\nα+β>1: 규모수익 체증\nα+β=1: 규모수익 불변\nα+β<1: 규모수익 체감","difficulty":2},
    {"number":8,"topicId":"micro_perfect_comp","keywords":["완전경쟁","장기균형","경제적이윤","P=MC=AC","진입퇴출"],"coreStatement":"완전경쟁 장기균형: P=MC=AC(최저점). 경제적이윤=0. 자유로운 진입·퇴출에 의해 달성.","answer":3,"basicExplanation":"장기: 이윤>0→진입→공급↑→P↓→이윤=0. 이윤<0→퇴출→공급↓→P↑→이윤=0. P=MC(이윤극대화)=AC(영이윤).","detailedExplanation":"【완전경쟁 장기균형】\n단기: P=MC로 이윤극대화\n장기: 자유진입·퇴출→경제적이윤=0\nP=MC=AC_min\n\n개별기업: 최적규모에서 생산\n산업: 기업 수 조정으로 시장청산\n\n장기공급곡선:\n비용불변산업→수평\n비용체증산업→우상향\n비용체감산업→우하향","difficulty":1},
    {"number":9,"topicId":"micro_monopoly","keywords":["독점","가격차별","MR=MC","자중손실","독점규제"],"coreStatement":"독점: MR=MC로 이윤극대화, P>MC→비효율(DWL). 1급가격차별(완전): 소비자잉여 전부 흡수, DWL=0.","answer":4,"basicExplanation":"독점 균형: MR=MC, P>MC. 사중손실=완전경쟁 대비 후생 손실. 가격차별: 1급(개인별), 2급(수량할인), 3급(시장분리).","detailedExplanation":"【독점 분석】\nMR=P(1-1/|Ed|)=MC\nP>MC→자원배분 비효율\nDWL=½(P_m-MC)(Q_c-Q_m)\n\n가격차별:\n1급: 각 소비자 유보가격 부과→DWL=0, CS=0\n2급: 수량별 가격→이부가격, 묶음판매\n3급: 시장별 다른 가격→|Ed|높은시장 낮은가격","difficulty":2},
    {"number":10,"topicId":"micro_game_theory","keywords":["게임이론","내쉬균형","죄수딜레마","우월전략","지배전략"],"coreStatement":"내쉬균형: 모든 참가자가 상대방의 전략이 주어졌을 때 자신의 전략을 바꿀 유인이 없는 상태.","answer":1,"basicExplanation":"우월전략: 상대 전략과 무관하게 항상 최선. 내쉬균형: 상호최적반응. 죄수딜레마: 개인합리성→사회적 비효율.","detailedExplanation":"【게임이론 핵심 개념】\n우월전략균형: 모든 참가자가 우월전략 보유→가장 강한 균형\n내쉬균형: 각자 상대방 전략에 대한 최적반응\n죄수딜레마: 두 참가자 모두 우월전략(배신)→파레토비효율적\n\n혼합전략: 확률적 전략 선택\n반복게임: 협조 가능성↑(무한반복+충분한 할인요소)","difficulty":2},
    {"number":11,"topicId":"tax_incidence","keywords":["조세귀착","탄력성","소비자부담","생산자부담","완전경쟁"],"coreStatement":"조세 부담 분배: 소비자부담비율=εs/(εs+|εd|). 비탄력적 쪽이 더 많이 부담.","answer":2,"basicExplanation":"소비자부담=εs/(εs+|εd|), 생산자부담=|εd|/(εs+|εd|). 수요 비탄력적→소비자 더 부담. 공급 비탄력적→생산자 더 부담.","detailedExplanation":"【조세귀착 공식】\n소비자부담비율 = εs/(εs+|εd|)\n생산자부담비율 = |εd|/(εs+|εd|)\n\n극단적 경우:\n수요 완전비탄력: 소비자 100%\n수요 완전탄력: 생산자 100%\n공급 완전비탄력: 생산자 100%\n공급 완전탄력: 소비자 100%\n\n법적 납세의무자와 무관(비법정 귀착)","difficulty":2},
    {"number":12,"topicId":"tax_theory","keywords":["조세원칙","아담스미스","공평","확실","편의","최소징세비"],"coreStatement":"아담 스미스 조세 4원칙: 공평의 원칙, 확실성의 원칙, 편의의 원칙, 최소징세비의 원칙.","answer":3,"basicExplanation":"①공평(능력에 비례) ②확실(세액·납기 확정적) ③편의(납세자에 편리한 시기·방법) ④최소징세비(징세비용 최소화). 머스그레이브: 효율+공평+안정 추가.","detailedExplanation":"【조세원칙 체계】\nA. Smith(1776):\n①공평 ②확실 ③편의 ④최소징세비\n\nWagner(19C):\n재정정책적: 충분성, 탄력성\n국민경제적: 세원선택, 세종선택\n공정의: 보편성, 공평성\n세무행정적: 확실, 편의, 최소징세비\n\nMusgrave(20C):\n효율성, 공평성, 경제안정, 행정편의","difficulty":1},
    {"number":13,"topicId":"tax_incidence","keywords":["독점시장","종량세","가격전가","초과전가","수요탄력성"],"coreStatement":"독점 하 종량세: 선형수요·일정MC에서 ΔP=t/2(부분전가). 수요곡선 볼록→초과전가(ΔP>t) 가능.","answer":4,"basicExplanation":"독점+종량세 t: MC→MC+t. 선형수요: ΔP=t/2. 볼록수요(일정탄력성): 초과전가 가능. 수요탄력성에 의존.","detailedExplanation":"【독점 조세전가】\n선형수요 P=a-bQ, MC 일정:\nMR=MC+t → Q↓, ΔP=t/2\n\n일정탄력성 수요:\nΔP=t/(1-1/|Ed|) → |Ed|>1이면 ΔP>t (초과전가)\n\n완전경쟁과 차이:\n완전경쟁: 전가율은 탄력성 비율\n독점: 수요곡선 형태(볼록/오목)에 크게 의존","difficulty":3},
    {"number":14,"topicId":"externality","keywords":["피구세","외부비용","최적오염","한계저감비용","한계피해"],"coreStatement":"최적오염수준: 한계저감비용=한계피해(MAC=MD). 피구세=최적오염에서의 한계피해로 설정.","answer":1,"basicExplanation":"오염 완전 제거가 최적이 아님. MAC=MD에서 사회적 최적. 피구세를 이 수준의 MD로 설정하면 기업이 자발적으로 최적 배출량 선택.","detailedExplanation":"【최적오염 이론】\n한계저감비용(MAC): 오염감축 1단위 추가비용, 감축량↑→MAC↑\n한계피해(MD): 오염 1단위 추가피해, 오염량↑→MD↑\n\n최적: MAC=MD\n피구세=최적오염에서 MD\n→기업: MAC≤세율이면 저감, MAC>세율이면 배출+세금\n→최적 오염수준 자발적 달성","difficulty":2},
    {"number":15,"topicId":"public_goods","keywords":["공공재","린달균형","무임승차","자발적 기여","과소공급"],"coreStatement":"린달균형: 각자 한계편익에 비례하여 비용 분담→효율적 공급. 그러나 선호 표출 유인 없어 현실 적용 곤란.","answer":2,"basicExplanation":"린달균형: 개인별 세금(가격)이 각자의 MB와 일치. 효율적이나 무임승차 유인으로 현실에서 구현 어려움.","detailedExplanation":"【린달 균형】\n각 소비자의 공공재 가격 = 자신의 MB\nΣ 개인별 가격 = MC (사무엘슨 조건)\n\n장점: 효율적 배분 달성, 자발적 합의\n단점: 선호표출 유인 없음(무임승차)\n→ MB를 과소신고할 유인\n→ 현실 적용 곤란\n\n대안: 수요표출 메커니즘(클라크세, VCG)","difficulty":2},
    {"number":16,"topicId":"public_choice","keywords":["애로불가능성","사회선택","민주주의","독재자","IIA"],"coreStatement":"애로의 불가능성정리: 완비성·이행성·파레토·IIA·비독재를 모두 만족하는 사회선택규칙은 존재하지 않는다.","answer":3,"basicExplanation":"애로 조건: ①보편적 정의역 ②파레토원칙 ③IIA(무관한 대안 독립) ④비독재. 이 4조건을 동시 만족하는 사회후생함수 불존재.","detailedExplanation":"【애로의 불가능성정리(1951)】\n조건:\nU(보편적 정의역): 모든 선호 조합 허용\nP(파레토원칙): 모두 선호하면 사회도 선호\nI(IIA): 두 대안 간 사회적 순서는 그 두 대안에 대한 개인선호에만 의존\nD(비독재): 한 개인의 선호가 항상 사회적 선호 결정하면 안 됨\n\n결론: U+P+I+D를 동시 만족하는 사회적 선호순서 불가능","difficulty":2},
    {"number":17,"topicId":"externality","keywords":["코즈정리","재산권","거래비용","외부성","자발적협상"],"coreStatement":"코즈정리: 거래비용=0+재산권 명확→자발적 협상으로 효율적 배분. 재산권 귀속은 분배에만 영향.","answer":1,"basicExplanation":"조건: 거래비용=0, 재산권 명확. 결과: 누구에게 재산권 주든 효율적 결과 동일. 분배만 다름. 현실: 거래비용 존재→성립 어려움.","detailedExplanation":"【코즈정리 핵심】\n거래비용=0 + 재산권 명확 → 효율적 배분\n재산권 귀속: 효율에 무관, 분배에만 영향\n\n한계:\n①거래비용 존재→협상 실패\n②다수 당사자→집합행동 문제\n③정보비대칭→전략적 행동\n④소득효과→재산권 귀속이 효율에도 영향 가능","difficulty":1},
    {"number":18,"topicId":"macro_is_lm","keywords":["IS-LM","재정정책","통화정책","구축효과","유동성함정"],"coreStatement":"IS-LM 모형: 재정정책→IS이동, 통화정책→LM이동. 유동성함정(LM수평)→재정 최대·통화 무효.","answer":2,"basicExplanation":"재정확대: IS 우이동→Y↑,r↑(구축효과). 통화확대: LM 우이동→Y↑,r↓. LM수직→재정무효·통화최대. LM수평→재정최대·통화무효.","detailedExplanation":"【IS-LM 정책효과】\n재정정책(G↑): IS우이동→Y↑, r↑(부분구축)\nLM수직: 완전구축(Y불변)\nLM수평: 구축없음(최대효과)\n\n통화정책(M↑): LM우이동→Y↑, r↓\nLM수직: 최대효과\nLM수평(유동성함정): 무효\n\nIS수직: 재정최대, 통화무효\nIS수평: 재정무효, 통화최대","difficulty":2},
    {"number":19,"topicId":"macro_ad_as","keywords":["AD-AS","총수요","총공급","스태그플레이션","필립스곡선"],"coreStatement":"부정적 공급충격→AS좌이동→물가↑+산출↓(스태그플레이션). 수요확대→AD우이동→물가↑+산출↑.","answer":4,"basicExplanation":"AD우이동: P↑, Y↑. AS좌이동: P↑, Y↓(스태그플레이션). 장기AS수직→장기에 통화량은 물가에만 영향(화폐중립성).","detailedExplanation":"【AD-AS 분석】\n단기AS: 우상향(임금경직 등)\n장기AS: 수직(자연산출량)\n\nAD우이동: P↑, Y↑(단기), P↑, Y불변(장기)\nAS좌이동: P↑, Y↓ = 스태그플레이션\n\n정책 대응:\n수요관리: AD이동→물가와 산출 같은 방향\n공급측: 규제완화, 기술개발→AS우이동","difficulty":2},
    {"number":20,"topicId":"macro_consumption","keywords":["소비이론","항상소득가설","생애주기가설","절대소득가설","상대소득가설"],"coreStatement":"프리드먼 항상소득가설: 소비는 항상소득에 비례. 일시소득↑→저축. 모딜리아니 생애주기: 생애소득 기준 소비 평탄화.","answer":3,"basicExplanation":"케인즈(절대소득): C=a+bY. 듀젠베리(상대소득): 소비의 비가역성(래칫효과). 프리드먼: C=kY_P. 모딜리아니: 생애소득 균등 배분.","detailedExplanation":"【소비이론 비교】\n케인즈(절대소득): C=a+bY, APC>MPC, APC↓\n듀젠베리(상대소득): 소비 비가역성, 래칫효과\n프리드먼(항상소득): C=kY_P, 일시소득→저축\n모딜리아니(생애주기): 생애소득 배분, 연령별 저축패턴\n\n장기: APC=MPC(항상소득/생애주기에서 설명)\n단기: APC>MPC(케인즈 퍼즐 해결)","difficulty":2},
    {"number":21,"topicId":"micro_monopoly","keywords":["독점","자연독점","규모의경제","MC가격","AC가격"],"coreStatement":"자연독점: AC 지속 하락→MC<AC. MC가격→효율적이나 적자. AC가격→손익분기이나 비효율.","answer":1,"basicExplanation":"규모의 경제→한 기업이 전체 시장 공급이 효율적. MC가격=효율적 자원배분, but 적자. AC가격=영이윤, but P>MC.","detailedExplanation":"【자연독점 규제】\nMC가격: P=MC<AC→적자→정부보조 필요\nAC가격: P=AC→영이윤→비용절감유인 없음\n이부가격: 기본료+사용료(=MC)→효율+적자보전\n램지가격: 역탄력성 비례→DWL최소\n\n규제포획이론: 규제기관이 피규제자에 포획","difficulty":2},
    {"number":22,"topicId":"micro_game_theory","keywords":["내쉬균형","혼합전략","순수전략","최적반응","보수행렬"],"coreStatement":"순수전략 내쉬균형이 없으면 혼합전략 내쉬균형이 존재한다(내쉬 존재정리).","answer":2,"basicExplanation":"순수전략: 확정적 전략 선택. 혼합전략: 확률적 선택. 내쉬(1950): 유한게임에서 혼합전략 균형 항상 존재.","detailedExplanation":"【내쉬균형 유형】\n순수전략균형: 확정적 전략 프로필\n혼합전략균형: 확률분포로 전략 선택\n\n내쉬 존재정리: 유한게임에서 최소 하나의 (혼합전략) NE 존재\n\n혼합전략 균형 계산:\n상대방을 무차별하게 만드는 확률 설정\nEU(전략1)=EU(전략2)에서 혼합확률 도출","difficulty":2},
    {"number":23,"topicId":"micro_producer","keywords":["비용함수","단기비용","장기비용","규모의경제","범위의경제"],"coreStatement":"장기비용: 모든 요소 가변→포락선(단기비용곡선들의 하한). 규모의경제: LRAC↓, 범위의경제: 공동생산비용<개별합.","answer":3,"basicExplanation":"단기: 고정요소 존재→SAC. 장기: 모든 요소 가변→LAC=SAC들의 포락선. LRAC U자형: 규모의경제→규모의불경제.","detailedExplanation":"【비용함수 관계】\nSTC=SFC+SVC\nSAC=SAC_F+SAC_V\nSMC=dSTC/dQ\n\nLAC: SAC들의 포락선(하한)\nLMC: LAC의 기울기\nLAC 최저점에서 LAC=LMC=SAC=SMC\n\n규모의경제: LAC↓, 내부규모의경제(기술적)+외부규모의경제(산업적)","difficulty":2},
    {"number":24,"topicId":"macro_is_lm","keywords":["승수효과","정부지출승수","조세승수","균형예산승수","한계소비성향"],"coreStatement":"정부지출승수=1/(1-c), 조세승수=-c/(1-c), 균형예산승수=1. c: 한계소비성향.","answer":4,"basicExplanation":"ΔY/ΔG=1/(1-c): 정부지출승수. ΔY/ΔT=-c/(1-c): 조세승수. |정부지출승수|>|조세승수|. 균형예산승수=1.","detailedExplanation":"【승수 체계(단순모형 Y=C+I+G)】\nC=a+c(Y-T)\nY=a+c(Y-T)+I+G\n→Y=(a-cT+I+G)/(1-c)\n\n정부지출승수: ΔY/ΔG=1/(1-c)\n조세승수: ΔY/ΔT=-c/(1-c)\n이전지출승수: ΔY/ΔTr=c/(1-c)\n균형예산승수: ΔG=ΔT→ΔY=1\n\nIS-LM에서는 이자율 변화로 승수 축소(구축효과)","difficulty":2},
    {"number":25,"topicId":"macro_money","keywords":["화폐수요","화폐공급","통화승수","본원통화","LM곡선"],"coreStatement":"통화량=본원통화×통화승수. 통화승수=1/(지급준비율+현금비율). 화폐수요: 거래적+예비적+투기적 동기.","answer":1,"basicExplanation":"M=m×H (M:통화량, m:통화승수, H:본원통화). 케인즈 화폐수요: L=kY-hi. LM곡선: 화폐시장균형 M/P=L(Y,r).","detailedExplanation":"【화폐시장】\n통화승수 m=(1+c)/(r+c) (c:현금비율, r:지준율)\n\n화폐수요:\n거래적: L_T=kY\n투기적: L_S=-hr\n총화폐수요: L=kY-hr\n\nLM곡선: M/P=kY-hr → r=(k/h)Y-M/(Ph)\n기울기=k/h: h↑(화폐수요 이자탄력↑)→LM완만\n\n유동성함정: h→∞, LM수평","difficulty":2},
    {"number":26,"topicId":"income_distribution","keywords":["로렌츠곡선","지니계수","소득불평등","십분위","5분위"],"coreStatement":"로렌츠곡선: 인구누적비율 vs 소득누적비율. 대각선에서 멀수록 불평등. 지니계수=불평등면적/삼각형면적, 0(평등)~1(불평등).","answer":2,"basicExplanation":"지니계수: 로렌츠곡선과 대각선 사이 면적/전체삼각형 면적. 0=완전평등, 1=완전불평등. 로렌츠곡선 비교: 교차 시 지니계수로도 판단 가능하나 로렌츠 지배는 불가.","detailedExplanation":"【소득불평등 지표】\n로렌츠곡선: 누적인구비율-누적소득비율\n지니계수: G=A/(A+B), A=대각선과 로렌츠곡선 사이\n0≤G≤1\n\n5분위배율: 상위20%소득/하위20%소득 (클수록 불평등)\n십분위분배율: 하위40%소득/상위20%소득 (작을수록 불평등)\n\n로렌츠 지배: 곡선 교차 없이 한쪽이 완전히 안쪽→불평등","difficulty":1},
    {"number":27,"topicId":"micro_welfare","keywords":["후생경제학","보상원리","칼도힉스","잠재적파레토","사회적후생"],"coreStatement":"칼도-힉스 보상원리: 이득자가 손실자를 보상하고도 남으면 사회적 개선(실제 보상 불필요). 쉬토프스키 역설 가능.","answer":3,"basicExplanation":"칼도기준: 이득자가 손실자 보상 가능→개선. 힉스기준: 손실자가 이득자에 보상 불가능→개선. 양쪽 모두 만족=쉬토프스키 기준.","detailedExplanation":"【보상원리】\n칼도(1939): 이득자→손실자 보상 후 이득 남음\n힉스(1940): 손실자→이득자 보상해도 저지 불가\n쉬토프스키(1941): 양방향 모두 만족\n\n한계: 실제 보상 안 하면 분배 변화→공평 문제\n쉬토프스키 역설: 칼도기준 A>B이면서 B>A 가능\n→효용가능경계가 교차할 때 발생","difficulty":3},
    {"number":28,"topicId":"public_choice","keywords":["중위투표자","과반수결","단봉선호","투표역설","블랙정리"],"coreStatement":"블랙의 중위투표자정리: 단봉선호+과반수결→중위투표자 선호가 사회적 선택. 다봉선호→투표역설.","answer":1,"basicExplanation":"단봉선호: 선호하는 대안에서 멀어질수록 효용↓. 이 조건에서 중위투표자의 최선 대안이 과반수결 승리.","detailedExplanation":"【중위투표자 정리】\n조건: ①단봉선호 ②단일쟁점(1차원) ③과반수결\n결론: 중위투표자 선호=과반수결 결과\n\n한계:\n- 다차원 쟁점→중위투표자 부재\n- 다봉선호→투표순환(역설)\n- 전략적 투표→비성실 투표\n\n과반수결 승자(콩도르세 승자)=중위투표자 최선","difficulty":2},
    {"number":29,"topicId":"externality","keywords":["배출권거래","캡앤트레이드","한계저감비용","비용효율성","피구세비교"],"coreStatement":"배출권거래: 총량(cap) 고정+거래(trade)→한계저감비용 균등화→비용효과적. 피구세와 불확실성 하 차이(와이츠만).","answer":4,"basicExplanation":"cap & trade: 정부가 총배출량 설정, 기업 간 배출권 거래. 균형: 모든 기업의 MAC=배출권 가격. 불확실성: MAC 불확실→수량규제(배출권), MD 불확실→가격규제(세금).","detailedExplanation":"【배출권거래 vs 피구세】\n공통점: 한계저감비용 균등화, 비용효과적\n차이점:\n피구세: 가격(세율) 고정, 배출량 불확실\n배출권: 배출량 고정, 가격 불확실\n\n와이츠만(1974):\nMAC 급경사+MD 완만 → 가격규제(세금) 유리\nMAC 완만+MD 급경사 → 수량규제(배출권) 유리","difficulty":2},
    {"number":30,"topicId":"public_choice","keywords":["니스카넨","관료제","예산극대화","과잉공급","정보비대칭"],"coreStatement":"니스카넨: 관료는 예산극대화 추구. 비용 정보 독점→의회에 과대예산 요구→공공재 과잉공급.","answer":3,"basicExplanation":"관료의 목적함수=예산규모. 의회: 총편익만 파악. 관료: 비용 독점→총편익=총비용까지 생산 요구→사회적최적의 2배.","detailedExplanation":"【니스카넨 모형】\n가정:\n①관료: 예산극대화(효용=f(예산))\n②관료: 비용 정보 독점\n③의회: 총편익 파악, 비용 모름\n\n결과: 총편익=총비용이 되는 수준까지 예산 요구\nQ_bureau = 2×Q_optimal (사회적 최적의 2배)\n\n비판: 관료 동기 다양, 의회의 정보수집 능력","difficulty":2},
    {"number":31,"topicId":"tax_theory","keywords":["최적조세","램지규칙","역탄력성","초과부담최소화","효율성"],"coreStatement":"램지규칙: 초과부담 최소화를 위해 수요탄력성이 낮은 재화에 높은 세율 부과(역탄력성 규칙).","answer":2,"basicExplanation":"최적간접세: DWL 최소화 조건. 역탄력성 규칙: t_i ∝ 1/ε_i. 탄력성 낮은 필수품→높은 세율→역진적(공평 문제).","detailedExplanation":"【램지 규칙(1927)】\n목적: 주어진 세수를 최소 DWL로 조달\n결론: 각 재화의 보상수요를 동일 비율로 감소(역탄력성 규칙)\nt_i/t_j = ε_j/ε_i\n\n한계:\n- 역진적: 필수품(비탄력적)에 높은 세율→저소득층 부담↑\n- 공평성 고려: 다이아몬드-미를리스 수정\n- 소득세 존재 시: 코렛-헤이그(여가 보완재에 높은 세율)","difficulty":3},
    {"number":32,"topicId":"income_distribution","keywords":["지니계수","앳킨슨","달톤","소득불평등","가치판단"],"coreStatement":"지니계수: 로렌츠곡선 기반, 0~1. 앳킨슨지수: 불평등혐오도(ε) 반영. 달톼지수: 공리주의 SWF 기반.","answer":4,"basicExplanation":"지니: 면적비율. 앳킨슨: 1-Y_EDE/Ȳ, ε 파라미터로 가치판단 명시. 달톤: W_실제/W_균등. 5분위배율: 상위/하위 소득비.","detailedExplanation":"【불평등 지수 비교】\n지니계수: 로렌츠곡선과 45도선 사이 면적 비율\n  장점: 직관적, 로렌츠곡선에서 직접 도출\n  단점: 분포 형태에 민감하지 않음\n\n앳킨슨: A=1-Y_EDE/Ȳ\n  ε=0: 불평등 무관심\n  ε→∞: 롤스적\n  장점: 가치판단 명시적\n\n달톤: I=1-W_실제/W_균등 (공리주의 SWF)","difficulty":2},
    {"number":33,"topicId":"social_insurance","keywords":["국민건강보험","사회보험","역선택","도덕적해이","보험료"],"coreStatement":"국민건강보험: 강제가입으로 역선택 해결. 도덕적해이 문제(과잉이용)→본인부담금 등으로 억제.","answer":3,"basicExplanation":"역선택: 고위험자만 가입→보험시장 실패→강제가입으로 해결. 도덕적해이: 보험가입 후 의료서비스 과잉이용→본인부담, 진료심사.","detailedExplanation":"【건강보험과 시장실패】\n역선택(가입 전): 정보비대칭→고위험자 집중→보험료↑→저위험자 이탈\n→강제가입으로 해결\n\n도덕적해이(가입 후): 비용의식↓→과잉이용\n→본인부담금(co-payment)\n→사전심사(utilization review)\n\n크림스키밍: 보험자가 저위험자만 선택→공적보험 필요","difficulty":2},
    {"number":34,"topicId":"fiscal_federalism","keywords":["지방재정","지방세","재산세","취득세","지방소득세"],"coreStatement":"지방세 원칙: 세원 분포 균등, 이동성 낮은 세원 적합(재산세), 소득재분배는 중앙정부가 적합.","answer":2,"basicExplanation":"지방세로 적합: 세원 지역 편중↓, 이동성↓. 재산세: 부동산은 이동 불가→지방세 적합. 소득세: 이동성↑→지방세 부적합.","detailedExplanation":"【지방세 원칙(머스그레이브)】\n①이동성 낮은 세원 (재산세, 토지세)\n②세원 지역 균등 분포\n③경기변동 민감도 낮은 세원\n④소득재분배→중앙 소관\n⑤안정화기능→중앙 소관\n⑥배분기능→지방 소관\n\n한국 지방세: 취득세, 재산세, 자동차세, 지방소득세 등\n지방소비세·지방소득세: 국세와 연계","difficulty":1},
    {"number":35,"topicId":"public_expenditure","keywords":["예산제도","PPBS","영기준","성과주의","발생주의"],"coreStatement":"PPBS: 기획·프로그래밍·예산 연계→장기계획 기반 합리적 자원배분. 영기준예산: 전년도 무관하게 매년 0에서 검토.","answer":1,"basicExplanation":"PPBS(계획예산): 목표설정→대안분석→프로그램→예산. ZBB(영기준): 모든 사업을 매년 처음부터 평가. 성과주의: 산출·성과 중심.","detailedExplanation":"【예산제도 발전순서】\n품목별(LIBS): 투입통제→1920s\n성과주의(PBS): 산출·원가→1950s\nPPBS: 기획+프로그램+예산→1960s(국방부)\nZBB: 영기준 검토→1970s(카터)\nNPB(신성과주의): 산출·성과+재량→1990s~\n\n발생주의: 거래발생시점 인식(현금주의: 현금수수시점)","difficulty":1},
    {"number":36,"topicId":"macro_national_income","keywords":["국민소득","GDP","GNI","NDP","실질GDP"],"coreStatement":"GDP: 국내 생산 기준. GNI: 국민 소득 기준(해외순소득 포함). NDP=GDP-감가상각. 실질GDP: 물가 변동 제거.","answer":4,"basicExplanation":"GDP=국내 총생산(속지주의). GNI=GDP+해외순수취요소소득(속인주의). NDP=GDP-고정자본소모. 실질GDP: 기준연도 가격 적용.","detailedExplanation":"【국민소득 계정】\nGDP: 국내에서 생산된 최종재 가치\n3면 등가: 생산=분배=지출\n\nGNI = GDP + 해외순수취요소소득\nNDP = GDP - 감가상각\nNI = NDP - 간접세 + 보조금\nPI = NI - 법인세 - 사내유보 + 이전지출\nDI = PI - 개인소득세\n\n실질GDP: 기준연도 가격×당해연도 수량\nGDP디플레이터 = 명목GDP/실질GDP × 100","difficulty":1},
    {"number":37,"topicId":"social_insurance","keywords":["공적연금","부과방식","적립방식","세대간이전","자산대체"],"coreStatement":"부과방식: 현세대 보험료→현세대 급여(세대간 이전). 적립방식: 자기 적립→자기 급여. 자산대체효과→민간저축↓.","answer":2,"basicExplanation":"부과방식(PAYG): 현역세대→은퇴세대, 인구구조에 민감. 적립방식: 자기 기여 적립, 투자수익에 민감. 자산대체효과: 연금이 저축 대체.","detailedExplanation":"【공적연금의 경제적 효과】\n자산대체효과: 공적연금→자가저축↓→민간저축↓\n은퇴효과: 조기은퇴 유인→노후대비 저축↑\n\n부과방식:\n- 세대간 이전: 현역→은퇴\n- 인구고령화→부양비↑→재정 불안\n- Aaron조건: n+g>r이면 부과방식 유리\n\n적립방식:\n- 세대내 저축: 자기 기여→자기 급여\n- 자본축적 기여 가능\n- 인플레이션·운용 위험","difficulty":2},
    {"number":38,"topicId":"public_expenditure","keywords":["정부지출","바그너법칙","전위효과","보몰비용병","재정착각"],"coreStatement":"바그너법칙: 소득↑→정부지출 비중↑(소득탄력성>1). 보몰: 정부서비스 생산성 낮아 상대비용↑.","answer":3,"basicExplanation":"바그너: 산업화→정부 기능 확대. 피콕-와이즈만: 전쟁 등 충격→조세허용↑→톱니효과. 보몰: 노동집약적 정부서비스→생산성↓상대비용↑.","detailedExplanation":"【정부지출 팽창 이론】\nバグナー법칙: 소득탄력성>1, 공공재=사치재\n피콕-와이즈만: 전위효과+검사효과+집중효과\n보몰 비용병: 정부서비스 노동집약→생산성↓→상대비용↑\n재정착각: 조세부담 과소인식→과대 공공서비스 수요\n리바이어던: 정부=세입극대화 괴물(뷰캐넌)","difficulty":2},
    {"number":39,"topicId":"public_expenditure","keywords":["비용편익분석","할인율","NPV","IRR","사회적할인율"],"coreStatement":"비용편익분석: 공공사업 타당성 평가. NPV>0 또는 IRR>사회적할인율이면 타당. 할인율↑→장기사업 불리.","answer":1,"basicExplanation":"NPV=Σ(B-C)/(1+r)^t. IRR: NPV=0 되는 할인율. NPV법이 IRR법보다 이론적으로 우월(규모·기간 차이 반영).","detailedExplanation":"【비용편익분석】\n평가기준:\n①NPV법: NPV>0→채택\n②IRR법: IRR>r→채택\n③B/C비율법: B/C>1→채택\n\nNPV vs IRR 불일치:\n규모 다른 사업, 편익 시점 다른 사업\n→NPV법 우선 적용\n\n사회적할인율:\n사회적시간선호율+사회적기회비용 가중평균\n시장이자율과 다를 수 있음","difficulty":2},
    {"number":40,"topicId":"income_distribution","keywords":["소득재분배","부의소득세","NIT","기초수당","한계세율"],"coreStatement":"부의소득세(NIT): 면세점 이하→정부가 보조금 지급. 대체+소득효과 모두 노동공급↓ 방향→근로의욕 저하 문제.","answer":4,"basicExplanation":"NIT: G=B-tY. 면세점=B/t. 대체효과: 실질임금↓→노동↓. 소득효과: 실질소득↑→여가↑→노동↓. 두 효과 모두 노동↓.","detailedExplanation":"【부의소득세(NIT)】\nG=B-tY (B:기초수당, t:한계세율)\n면세점(BEI)=B/t\n\n노동공급 효과:\n대체효과: 실질임금w(1-t)↓→여가↑→노동↓\n소득효과: 기초수당B→소득↑→여가↑(정상재)→노동↓\n→두 효과 모두 노동공급 감소\n\nEITC와 비교:\n점증구간에서 대체효과→노동↑\n→NIT보다 근로유인 우수","difficulty":2}
]

parsed = json.loads(Path('d:/Coding/semusa/web/data/parsed/parsed_2023_재정학.json').read_text(encoding='utf-8'))
parsed_map = {q['number']: q for q in parsed['questions']}

all_q = []
for eq in ENRICHMENT:
    orig = parsed_map.get(eq['number'], {})
    all_q.append({**orig, **eq})
all_q.sort(key=lambda x: x['number'])

result = {'year': 2023, 'subject': '재정학', 'totalQuestions': len(all_q), 'questions': all_q}
out = Path('d:/Coding/semusa/web/data/enriched/enriched_2023_재정학.json')
out.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding='utf-8')
print(f'OK {len(all_q)} questions -> {out}')
