"""2024 재정학 enrichment"""
import json
from pathlib import Path

ENRICHMENT = [
    {"number":1,"topicId":"micro_demand_supply","keywords":["수요공급","균형","가격규제","최저가격","최고가격"],"coreStatement":"최고가격제(가격상한): 균형가격 아래 설정→초과수요(부족). 최저가격제(가격하한): 균형가격 위→초과공급(잉여).","answer":3,"basicExplanation":"최고가격<균형가격→수요>공급→부족. 최저가격>균형가격→공급>수요→잉여. 최저임금제는 최저가격제의 예.","detailedExplanation":"【가격규제】\n최고가격제: P_max < P* → Q_d > Q_s → 초과수요(부족)\n예: 임대료상한제, 이자율상한\n부작용: 암시장, 품질저하, 배급제\n\n최저가격제: P_min > P* → Q_s > Q_d → 초과공급(잉여)\n예: 최저임금제, 농산물가격지지\n부작용: 실업, 재고누적","difficulty":1},
    {"number":2,"topicId":"micro_elasticity","keywords":["수요탄력성","총수입","단위탄력","탄력적","비탄력적"],"coreStatement":"탄력적(|Ed|>1): 가격↓→TR↑. 비탄력적(|Ed|<1): 가격↓→TR↓. 단위탄력(|Ed|=1): TR 불변.","answer":2,"basicExplanation":"|Ed|>1: 수량변화율>가격변화율→가격↓시 TR↑. |Ed|<1: 반대. 총수입 극대: |Ed|=1(MR=0).","detailedExplanation":"【탄력성과 총수입】\nTR=P×Q\n|Ed|>1(탄력적): P↓→Q↑폭>P↓폭→TR↑\n|Ed|<1(비탄력적): P↓→Q↑폭<P↓폭→TR↓\n|Ed|=1(단위탄력): TR 불변, MR=0\n\nMR=P(1-1/|Ed|)\n|Ed|>1→MR>0, |Ed|<1→MR<0","difficulty":1},
    {"number":3,"topicId":"micro_consumer","keywords":["무차별곡선","한계대체율","볼록성","완전대체","완전보완"],"coreStatement":"무차별곡선: 동일 효용을 주는 재화 조합. 볼록성→체감하는 MRS. 완전대체: 직선. 완전보완: L자형.","answer":4,"basicExplanation":"MRS=-ΔY/ΔX=MU_x/MU_y (체감). 볼록성: 다양한 소비 선호. 완전대체: MRS 일정(직선). 완전보완: 고정비율(L자형, MRS=0 또는 ∞).","detailedExplanation":"【무차별곡선 특성】\n①우하향: 한 재화↑→다른 재화↓(효용 유지)\n②교차 불가: 이행성 위배\n③원점에서 멀수록 높은 효용\n④원점 방향 볼록: MRS 체감\n\n특수 선호:\n완전대체: U=aX+bY, MRS=a/b(일정), 직선\n완전보완: U=min(aX,bY), L자형, 꼭짓점에서 소비","difficulty":1},
    {"number":4,"topicId":"micro_consumer","keywords":["소득소비곡선","엥겔곡선","정상재","열등재","소득효과"],"coreStatement":"소득↑→수요↑이면 정상재(소득탄력성>0), 소득↑→수요↓이면 열등재(소득탄력성<0). 엥겔곡선: 소득-수요량 관계.","answer":1,"basicExplanation":"소득소비곡선(ICC): 소득 변화 시 최적 소비점의 궤적. 엥겔곡선: 소득-수요량. 정상재: 우상향 엥겔곡선. 열등재: 우하향.","detailedExplanation":"【소득효과 분석】\n정상재: 소득↑→수요↑, ε_m>0\n  필수재: 0<ε_m<1\n  사치재: ε_m>1\n열등재: 소득↑→수요↓, ε_m<0\n\n엥겔의 법칙: 소득↑→식료품 지출비중↓\n소득소비곡선: 가격 고정, 소득 변화→최적점 이동 궤적","difficulty":1},
    {"number":5,"topicId":"micro_producer","keywords":["생산함수","한계생산","평균생산","수확체감","등량곡선"],"coreStatement":"한계생산체감법칙: 다른 요소 고정 시 한 요소↑→MP 결국 감소. AP 최대점에서 AP=MP.","answer":3,"basicExplanation":"TP: 총생산, AP=TP/L, MP=dTP/dL. MP>AP→AP↑, MP<AP→AP↓, MP=AP→AP 최대. 수확체감: MP↓.","detailedExplanation":"【생산함수 관계】\nMP>AP→AP 증가(평균 끌어올림)\nMP=AP→AP 최대\nMP<AP→AP 감소(평균 끌어내림)\nMP=0→TP 최대\n\n등량곡선: 동일 산출량 생산하는 K,L 조합\nMRTS=MP_L/MP_K (체감)\n\n규모수익: 모든 투입 n배→산출 변화","difficulty":2},
    {"number":6,"topicId":"micro_perfect_comp","keywords":["완전경쟁","이윤극대화","P=MC","공급곡선","생산자잉여"],"coreStatement":"완전경쟁 기업: P=MC(AVC 이상 구간)가 공급곡선. 단기: P≥AVC이면 생산. 장기: P=MC=AC.","answer":2,"basicExplanation":"이윤극대: MR=MC, 완전경쟁에서 MR=P→P=MC. 조업중단점: P=AVC(최저). 손익분기점: P=AC(최저).","detailedExplanation":"【완전경쟁 기업의 의사결정】\nP>AC: 초과이윤, 장기 진입 유인\nP=AC: 정상이윤(영이윤)\nAVC<P<AC: 손실이나 조업(고정비 일부 회수)\nP<AVC: 조업중단(생산 안 하는 게 나음)\n\n단기공급곡선: MC곡선의 AVC 이상 부분\n장기공급곡선: 비용불변→수평, 비용체증→우상향","difficulty":1},
    {"number":7,"topicId":"micro_monopoly","keywords":["독점","MR","가격설정력","수요탄력성","러너지수"],"coreStatement":"독점: MR=P(1-1/|Ed|)=MC. 러너지수 L=(P-MC)/P=1/|Ed|. 탄력성↑→마크업↓.","answer":4,"basicExplanation":"독점 이윤극대: MR=MC. P>MR=MC→비효율. 러너지수: 독점력 측정. |Ed| 큰(탄력) 시장→낮은 가격(3급 가격차별).","detailedExplanation":"【독점 분석】\nMR = P + Q(dP/dQ) = P(1-1/|Ed|)\nMR=MC → P(1-1/|Ed|) = MC\nP = MC/(1-1/|Ed|) = MC·|Ed|/(|Ed|-1)\n\n러너지수: L = (P-MC)/P = 1/|Ed|\n완전경쟁: L=0, 독점: L>0\n\n3급 가격차별: MR_1=MR_2=MC\n탄력적 시장→낮은 가격","difficulty":2},
    {"number":8,"topicId":"micro_game_theory","keywords":["게임이론","순차게임","역진귀납","신빙성있는위협","부분게임완전균형"],"coreStatement":"순차게임: 역진귀납법(backward induction)으로 부분게임완전균형(SPNE) 도출. 비신빙성 위협은 균형에서 배제.","answer":1,"basicExplanation":"역진귀납: 마지막 단계부터 최적 선택→앞 단계 예측. SPNE: 모든 부분게임에서 내쉬균형. 빈 위협 배제.","detailedExplanation":"【순차게임 분석】\n동시게임: 보수행렬→내쉬균형\n순차게임: 게임트리→역진귀납→SPNE\n\n부분게임완전균형(SPNE):\n모든 부분게임에서 NE 충족\n비신빙성 위협 배제\n\n진입저지 게임 예:\n기존기업의 '진입 시 가격전쟁' 위협\n→역진귀납: 진입 후 수용이 합리적→위협 비신빙성","difficulty":2},
    {"number":9,"topicId":"micro_welfare","keywords":["후생경제학","제1정리","제2정리","파레토효율","경쟁균형"],"coreStatement":"제1정리: 경쟁균형→파레토효율. 제2정리: 파레토효율적 배분→재분배+경쟁으로 달성 가능.","answer":3,"basicExplanation":"제1: 완전경쟁 균형은 효율적(정부 개입 불필요). 제2: 효율과 공평 분리 가능(일괄이전 후 시장에 맡기면 됨).","detailedExplanation":"【후생경제학 기본정리】\n제1정리: 모든 경쟁균형→파레토효율\n  조건: 완전경쟁, 완전정보, 외부성 없음\n  의미: 보이지 않는 손의 효율성\n\n제2정리: 모든 파레토효율적 배분→적절한 lump-sum 재분배+경쟁→달성\n  조건: 볼록선호, 볼록생산집합\n  의미: 효율과 분배 분리 가능","difficulty":2},
    {"number":10,"topicId":"tax_incidence","keywords":["조세귀착","탄력성","완전탄력","완전비탄력","세금전가"],"coreStatement":"공급완전탄력(수평): 소비자 100% 부담. 수요완전비탄력(수직): 소비자 100% 부담. 비탄력적 쪽이 더 부담.","answer":4,"basicExplanation":"소비자부담=εs/(εs+|εd|). 공급 완전탄력(εs=∞): 소비자100%. 수요 완전비탄력(|εd|=0): 소비자100%.","detailedExplanation":"【극단적 탄력성과 조세귀착】\n수요 완전비탄력(εd=0, 수직): 소비자 100%\n수요 완전탄력(εd=∞, 수평): 생산자 100%\n공급 완전비탄력(εs=0, 수직): 생산자 100%\n공급 완전탄력(εs=∞, 수평): 소비자 100%\n\n법적 납세의무자와 무관: 경제적 귀착은 탄력성에 의존","difficulty":2},
    {"number":11,"topicId":"tax_theory","keywords":["조세원칙","효율성","중립성","공평성","간편성"],"coreStatement":"좋은 조세의 조건: 효율성(초과부담 최소), 공평성(수평·수직), 간편성(징세·납세비용 최소), 충분성(재정수요 충족).","answer":2,"basicExplanation":"효율성=경제적 의사결정 왜곡 최소(중립성). 공평성=동일능력 동일과세+차등능력 차등과세. 간편성=행정비용↓.","detailedExplanation":"【바람직한 조세의 조건】\n①효율성: DWL 최소화, 중립적 세제\n②공평성: 수평적(같은 능력→같은 세금)+수직적(다른 능력→다른 세금)\n③간편성: 납세비용+징세비용 최소\n④충분성: 정부 재정수요 충족\n⑤신축성: 경제변화에 탄력적 대응\n\n상충관계: 효율 vs 공평(역탄력성 규칙의 역진성)","difficulty":1},
    {"number":12,"topicId":"tax_theory","keywords":["누진세","한계세율","평균세율","세수탄력성","자동안정장치"],"coreStatement":"누진세: 소득↑→평균세율↑. 한계세율>평균세율. 세수탄력성>1. 경기자동안정장치 기능.","answer":3,"basicExplanation":"누진세 판별: t_m > t̄ ↔ dt̄/dY>0 ↔ η>1. 호황→소득↑→세율↑→가처분소득↑폭<소득↑폭→자동적 경기억제.","detailedExplanation":"【누진세의 특성】\n정의: 소득 증가 시 평균세율 증가\nt_m(한계세율) > t̄(평균세율)\nη(세수탄력성) = t_m/t̄ > 1\n\n자동안정장치:\n호황: Y↑→T/Y↑→가처분소득↑폭 억제→총수요 억제\n불황: Y↓→T/Y↓→가처분소득↓폭 완화→총수요 지지\n\n비례세: t_m=t̄, η=1\n역진세: t_m<t̄, η<1","difficulty":2},
    {"number":13,"topicId":"tax_incidence","keywords":["초과부담","사중손실","세율","탄력성","보상변화"],"coreStatement":"초과부담(DWL)∝t²×ε. 세율 2배→DWL 4배. 탄력성↑→DWL↑. 정액세(lump-sum): DWL=0.","answer":1,"basicExplanation":"DWL=½t²εPQ. 세율의 제곱에 비례→세율 높을수록 급격히 증가. 탄력성 높을수록 거래량 변화 크므로 DWL↑.","detailedExplanation":"【초과부담 분석】\nDWL = ½ × t² × ε_c × P × Q\n\n세율 2배→DWL 4배(제곱 관계)\n보상탄력성 ε_c 사용(정확한 측정)\n\n정액세: 상대가격 불변→DWL=0(가장 효율적)\nbut 공평성 문제(모두 동일 세액)\n\n최적과세: DWL 최소+세수 충족+공평 고려","difficulty":2},
    {"number":14,"topicId":"externality","keywords":["외부성","피구세","피구보조금","사회적비용","내재화"],"coreStatement":"부정적 외부성→SMC>PMC→과잉생산. 피구세=한계외부비용. 긍정적 외부성→SMB>PMB→과소생산. 피구보조금=한계외부편익.","answer":4,"basicExplanation":"부정적: PMC+피구세=SMC→사회적 최적. 긍정적: PMB+보조금=SMB→사회적 최적. 외부비용/편익을 가격에 반영(내재화).","detailedExplanation":"【외부성 교정】\n부정적 외부성:\nSMC = PMC + MEC\n시장: PMC=PMB → Q_m > Q* (과잉)\n피구세 = MEC(최적에서) → PMC+t=SMC → Q*\n\n긍정적 외부성:\nSMB = PMB + MEB\n시장: PMC=PMB → Q_m < Q* (과소)\n피구보조금 = MEB(최적에서) → PMB+s=SMB → Q*","difficulty":2},
    {"number":15,"topicId":"public_goods","keywords":["공공재","사무엘슨조건","수직합산","최적공급","한계편익"],"coreStatement":"공공재 최적: ΣMRS_i = MRT (모든 소비자의 한계편익 합 = 한계비용). 수직합산.","answer":3,"basicExplanation":"사적재: 수평합산(같은 P에서 Q 합). 공공재: 수직합산(같은 Q에서 WTP 합). 비경합성→동시소비→각자의 MB를 합산.","detailedExplanation":"【사무엘슨 조건】\n사적재: MRS_A = MRS_B = MRT (수평합산)\n공공재: MRS_A + MRS_B = MRT (수직합산)\n\n직관: 공공재 1단위 추가 생산의 사회적 편익\n= 모든 소비자의 MB 합(동시소비)\n이것이 MC와 같을 때 최적\n\n문제: 무임승차→MB 과소신고→시장 실패","difficulty":2},
    {"number":16,"topicId":"public_choice","keywords":["투표이론","중위투표자","단봉선호","과반수결","콩도르세"],"coreStatement":"중위투표자정리: 단봉선호+1차원 쟁점+과반수결→중위투표자의 최선이 사회적 선택.","answer":2,"basicExplanation":"단봉선호: 최선에서 멀어질수록 효용↓. 중위투표자가 과반수결에서 항상 승리. 다봉선호→투표역설(순환) 가능.","detailedExplanation":"【중위투표자 정리】\n블랙(1948): 단봉선호→과반수결에서 안정적 결과\n중위투표자의 최선 대안=과반수결 승자\n\n한계:\n①다차원→중위 정의 불가\n②다봉선호→순환\n③전략적 투표→비성실\n④투표율→합리적 무지\n\n공공재 과잉/과소: 중위투표자≠평균→비효율 가능","difficulty":2},
    {"number":17,"topicId":"public_goods","keywords":["공공재","린달균형","무임승차","수요표출","클라크세"],"coreStatement":"린달균형: 각자 한계편익만큼 부담→효율적. 무임승차 유인으로 현실 구현 곤란. 클라크세: 선호 정직 표출 유도.","answer":1,"basicExplanation":"린달: 개인별 가격=MB_i, Σ개인가격=MC. 효율적이나 선호 과소표출 문제. 클라크세(피봇 메커니즘): 자신의 결정이 타인에 미치는 비용 부과.","detailedExplanation":"【공공재 수요표출 메커니즘】\n린달: 자발적 합의 기반→무임승차→실패\n\n클라크세(Clarke tax):\n각자 공공재 편익 신고\n피봇 조건: 자신 신고가 결과 바꿀 때만 세금 부과\n세금 = 자신 때문에 타인이 입는 손해\n→정직 신고가 우월전략\n\n한계: 세수 처리 문제, 담합 가능성","difficulty":2},
    {"number":18,"topicId":"macro_is_lm","keywords":["IS-LM","재정정책","통화정책","구축효과","정책효과"],"coreStatement":"재정정책: IS이동, 구축효과(r↑→I↓). 통화정책: LM이동. LM수평(유동성함정): 재정최대·통화무효.","answer":4,"basicExplanation":"G↑→IS우이동→Y↑,r↑→I↓(구축). M↑→LM우이동→r↓→I↑→Y↑. 구축효과 크기: LM기울기에 의존.","detailedExplanation":"【IS-LM 정책효과 정리】\n\nIS기울기 결정: 투자의 이자율탄력성(b), 한계소비성향(c)\nLM기울기 결정: 화폐수요의 소득탄력성(k), 이자율탄력성(h)\n\n재정정책(IS이동):\nLM수직: 완전구축→무효\nLM수평: 구축없음→최대\nIS가파를수록 효과↓\n\n통화정책(LM이동):\nLM수직: 최대효과\nLM수평: 무효\nIS완만할수록 효과↑","difficulty":2},
    {"number":19,"topicId":"macro_ad_as","keywords":["총수요총공급","물가","산출","공급충격","스태그플레이션"],"coreStatement":"AD: P↑→실질잔고↓→r↑→I↓→Y↓. 단기AS: 우상향(임금경직). 장기AS: 수직(자연산출).","answer":2,"basicExplanation":"AD우이동: P↑,Y↑. AS좌이동: P↑,Y↓(스태그플레이션). 장기: Y=Y_n에서 AS수직→화폐중립성.","detailedExplanation":"【AD-AS 모형】\nAD: IS-LM에서 물가변화→LM이동→Y변화\nP↑→M/P↓→LM좌이동→r↑→Y↓\n\n단기AS: 임금경직(케인즈), 불완전정보(루카스)\n장기AS: 수직(Y=Y_n, 자연산출량)\n\n공급충격: 유가상승→AS좌이동→P↑,Y↓\n정책딜레마: 물가안정 vs 산출회복","difficulty":2},
    {"number":20,"topicId":"macro_consumption","keywords":["소비함수","케인즈","항상소득","생애주기","APC"],"coreStatement":"케인즈: C=a+bY, APC>MPC 체감. 프리드먼: C=kY_P, APC=k(일정). 모딜리아니: 생애소득 균등소비.","answer":3,"basicExplanation":"케인즈 퍼즐: 단기 APC>MPC, 장기 APC≈MPC. 항상소득·생애주기 가설이 해결: 장기에 APC=MPC.","detailedExplanation":"【소비이론 비교】\n케인즈(1936): C=a+bY\n  APC=a/Y+b>b=MPC (APC 체감)\n  단기에만 적합\n\n프리드먼(1957): C=kY_P\n  항상소득에만 반응, 일시소득→저축\n  APC=k(일정)→장기적합\n\n모딜리아니(1963): C=(1/T)×(생애소득)\n  젊은시절 차입, 중년 저축, 노년 소비\n  APC: 연령에 따라 변화","difficulty":2},
    {"number":21,"topicId":"tax_theory","keywords":["조세제도","소득세","소비세","효율성","저축중립"],"coreStatement":"소득세: 소득 전체(근로+자본) 과세→저축 이중과세. 소비세: 소비만 과세→저축에 중립적(시점간 배분 불왜곡).","answer":2,"basicExplanation":"소득세: 이자소득 과세→저축수익↓→저축 왜곡. 지출세(소비세): 소비시점에 과세→저축 중립. 효율성 측면 소비세 유리.","detailedExplanation":"【소득세 vs 소비세】\n포괄적 소득세(Haig-Simons):\n소득=소비+순자산증가\n이자소득 과세→저축 이중과세→시점간 왜곡\n\n지출세(소비세, Kaldor):\n과세=소비만, 저축은 비과세\n시점간 소비선택 왜곡 없음→저축 중립\n\n실무적 차이:\n소비세: 역진적(소비비중 역비례)\n소득세: 누진적 과세 용이","difficulty":2},
    {"number":22,"topicId":"optimal_tax","keywords":["최적과세","램지규칙","역탄력성","코렛-헤이그","여가보완"],"coreStatement":"램지규칙: 역탄력성 원칙(비탄력적 재화에 높은 세율). 코렛-헤이그: 여가의 보완재에 높은 세율→간접적 여가 과세.","answer":4,"basicExplanation":"램지: DWL최소→탄력성 역수 비례 세율. 코렛-헤이그: 소득세 존재 시 여가 보완재에 높은 세율(여가 과세 불가하므로).","detailedExplanation":"【최적간접세 이론】\nRamsey(1927): min DWL s.t. 세수=R\n결론: 각 재화 보상수요를 동일비율 감소\n→역탄력성 규칙: t_i ∝ 1/ε_i\n\nCorlett-Hague(1953): 소득세 존재 시\n여가 보완재→높은 세율\n여가 대체재→낮은 세율\n→여가를 간접적으로 과세하는 효과\n\nDiamond-Mirrlees: 분배 고려→수정 역탄력성","difficulty":3},
    {"number":23,"topicId":"tax_incidence","keywords":["하버거모형","일반균형","법인세","자본귀착","노동귀착"],"coreStatement":"하버거 모형: 폐쇄경제+완전경쟁+요소이동에서 법인세 장기 귀착은 모든 자본(법인+비법인)이 부담.","answer":1,"basicExplanation":"법인세→법인부문 자본수익률↓→비법인으로 이동→양부문 세후수익률 균등화. 폐쇄경제: 자본 전체 부담.","detailedExplanation":"【하버거 일반균형 분석】\n가정: 2부문(법인X, 비법인Y), 2요소(K,L)\n\n법인세 효과:\n①산출효과: X재 가격↑→수요↓→X축소\n②요소대체효과: K 상대비용↑→L로 대체\n\n법인부문 자본수익률↓→K 비법인 이동\n→양부문 세후수익률 r* 균등화\n→모든 자본이 r*-r 만큼 부담\n\n개방경제: 자본 해외유출→국내 노동에도 귀착","difficulty":3},
    {"number":24,"topicId":"externality","keywords":["코즈정리","재산권","거래비용","외부성","효율적배분"],"coreStatement":"코즈정리: 재산권 명확+거래비용=0→협상으로 효율적 배분. 재산권 귀속은 분배에만 영향.","answer":2,"basicExplanation":"거래비용=0, 재산권 명확→외부성 당사자 간 자발적 협상→사회적 최적. 누구에게 재산권 주든 효율(Q*)은 동일, 분배만 다름.","detailedExplanation":"【코즈정리(1960)】\n조건: ①거래비용=0 ②재산권 명확\n결과: 자발적 협상→효율적 자원배분\n\n재산권 귀속:\n효율(생산량): 무관→항상 Q*\n분배(소득): 재산권 보유자에 유리\n\n한계:\n거래비용>0→협상 실패\n다수 당사자→집합행동 문제\n정보비대칭→전략적 행동\n소득효과→효율에도 영향 가능","difficulty":1},
    {"number":25,"topicId":"income_distribution","keywords":["소득분배","로렌츠곡선","지니계수","불평등","십분위"],"coreStatement":"지니계수: 로렌츠곡선과 45도선 사이 면적/삼각형 면적. 0=평등, 1=불평등. 로렌츠곡선 교차 시 순위 불확정.","answer":4,"basicExplanation":"로렌츠: 누적인구%-누적소득%. 대각선 가까울수록 평등. 지니=2A(A=곡선과 대각선 사이). 교차 시 지니 계산 가능하나 로렌츠 지배 불가.","detailedExplanation":"【소득불평등 지표】\n지니계수: G=A/(A+B)=2A=1-2B\n0: 완전평등, 1: 완전불평등\n\n5분위배율: 상위20%소득/하위20%소득\n십분위분배율: 하위40%소득/상위20%소득\n완전평등 시: 5분위=1, 십분위=2\n\n로렌츠 지배: 곡선A가 B 안쪽→A가 더 불평등\n교차 시: 지배 관계 없음(지니로는 비교 가능)","difficulty":1},
    {"number":26,"topicId":"income_distribution","keywords":["공리주의","롤스","노직","사회정의","재분배"],"coreStatement":"공리주의: 효용합 극대화. 롤스: 최소극대화(최하층 극대). 노직: 절차적 정의(결과 무관, 과정 공정하면 정의).","answer":3,"basicExplanation":"공리주의: W=ΣU→불평등 허용 가능. 롤스: maximin→최빈층 극대. 노직: 취득·이전·교정의 정의.","detailedExplanation":"【분배정의론 비교】\n벤담(공리주의): W=ΣU_i\n  효용합 극대→극단적 불평등 가능\n  동일한계효용 가정 시 균등분배\n\n롤스: W=min(U_i), 차등원칙\n  무지의 장막→최하층 극대화\n  기본적 자유→분배 우선\n\n노직: 절차적 정의\n  취득정의+이전정의+교정정의\n  결과 불문→최소국가 옹호","difficulty":2},
    {"number":27,"topicId":"public_choice","keywords":["관료제","니스카넨","예산극대화","렌트추구","정부실패"],"coreStatement":"니스카넨: 관료=예산극대화→과잉공급. 렌트추구: 독점이윤 획득 위한 비생산적 활동→사회적 낭비.","answer":1,"basicExplanation":"니스카넨 관료모형: 비용정보 독점→과대예산→사회적 최적의 2배 생산. 렌트추구(Tullock): 독점권·인허가 획득 위한 로비→자원낭비.","detailedExplanation":"【정부실패 이론】\n관료 모형(니스카넨):\n관료 효용=f(예산), 비용정보 독점\n→총편익=총비용까지 확대→Q=2Q*\n\n렌트추구(Tullock, Krueger):\n정부규제→렌트(초과이윤) 발생\n→렌트 획득 위한 로비·뇌물 등\n→사회적 자원낭비(DWL+렌트추구비용)\n\n정부실패: 정보부족, 관료이기심, 정치적 영향, 시차","difficulty":2},
    {"number":28,"topicId":"fiscal_federalism","keywords":["지방재정","티부가설","발로투표","분권화정리","최적지방정부"],"coreStatement":"티부(1956): 주민이 선호에 맞는 지역 이동(발로 투표)→공공재 효율적 공급. 오츠 분권화정리: 지역별 차별적 공급이 효율적.","answer":4,"basicExplanation":"티부: 다수 지역+자유이동+완전정보→발로 투표→효율. 오츠: 중앙 획일 공급 < 지방 차별 공급 (선호 이질적일 때).","detailedExplanation":"【지방재정 이론】\n티부가설(1956):\n가정: 다수 지역, 자유이동, 완전정보, 비용차이 없음\n결과: 발로 투표→선호표출→공공재 효율적 공급\n한계: 이동비용, 고용제약, 외부효과\n\n오츠 분권화정리:\n지역 간 선호 이질적→지방정부 차별 공급이 효율\n파급효과(외부성) 없다면 분권이 우월\n\n보조금: 파급효과 교정→중앙정부 역할","difficulty":2},
    {"number":29,"topicId":"macro_national_income","keywords":["GDP","GNI","생산접근","지출접근","분배접근"],"coreStatement":"GDP: 일정기간 국내에서 생산된 최종재·서비스 시장가치. 3면등가: 생산=분배=지출.","answer":2,"basicExplanation":"생산접근: 부가가치 합. 지출접근: C+I+G+(X-M). 분배접근: 임금+이자+지대+이윤. 실질GDP: 기준연도 가격 적용.","detailedExplanation":"【국민소득 회계】\nGDP(생산): Σ부가가치 = Σ(산출-중간투입)\nGDP(지출): Y = C + I + G + (X-M)\nGDP(분배): Y = w + r + i + π\n\nGNI = GDP + 해외순수취요소소득\nNDP = GDP - 감가상각\n\nGDP디플레이터 = 명목GDP/실질GDP × 100\nCPI: 고정바스켓→라스파이레스→상향편의","difficulty":1},
    {"number":30,"topicId":"macro_money","keywords":["통화정책","본원통화","통화승수","공개시장조작","지급준비율"],"coreStatement":"통화량=본원통화×통화승수. 공개시장매입→본원통화↑→통화량↑. 지준율↓→통화승수↑→통화량↑.","answer":1,"basicExplanation":"M=m×H. m=(1+c)/(r_r+c). 공개시장매입: H↑. 지준율↓: m↑. 재할인율↓: 차입↑→H↑.","detailedExplanation":"【통화정책 수단】\n공개시장조작: 국채 매입/매각→H 변화\n지급준비율: r_r 변경→m 변화\n재할인율: 중앙은행 대출이자→H 변화\n\n통화승수: m=(1+c)/(r_r+c)\nc: 현금비율(↑→m↓)\nr_r: 법정지준율(↑→m↓)\n\n양적완화: 비전통적→자산매입→H↑↑","difficulty":2},
    {"number":31,"topicId":"social_insurance","keywords":["공적연금","적립방식","부과방식","자산대체효과","은퇴효과"],"coreStatement":"자산대체효과: 공적연금→민간저축↓. 은퇴효과: 조기은퇴→노후대비 저축↑. 순효과는 두 힘의 상대적 크기에 의존.","answer":3,"basicExplanation":"자산대체: 연금=저축 대체→민간저축↓. 은퇴효과: 일찍 은퇴→더 긴 노후→저축↑. 총효과 불확실.","detailedExplanation":"【공적연금의 저축효과】\n자산대체효과: 연금자산이 개인저축 대체→저축↓\n은퇴효과: 연금→조기은퇴→노후 대비 저축↑\n\n부과방식(PAYG):\n적립 없음→정부저축 불변→민간저축↓→국민저축↓\n\n적립방식:\n정부저축↑→민간저축↓ 상쇄 가능→국민저축 효과 작음\n\nAaron조건: 인구증가율+임금상승률>이자율→부과방식 유리","difficulty":2},
    {"number":32,"topicId":"income_distribution","keywords":["앳킨슨지수","불평등혐오도","EDE","사회후생","가치판단"],"coreStatement":"앳킨슨 A=1-Y_EDE/Ȳ. ε↑→불평등 혐오↑→A↑. ε=0: A=0(무관심). ε→∞: 롤스적(최저소득에만 관심).","answer":4,"basicExplanation":"균등분배대등소득(Y_EDE): 현재 분배와 동일 사회후생을 주는 균등분배 소득. A가 클수록 불평등.","detailedExplanation":"【앳킨슨 지수】\nA = 1 - Y_EDE/Ȳ\n\nY_EDE = [Σ(y_i^(1-ε)/n)]^(1/(1-ε))\n\nε=0: Y_EDE=Ȳ, A=0 (불평등 무관심)\n0<ε<∞: 0<A<1\nε→∞: Y_EDE=min(y_i), A=1-min/Ȳ (롤스적)\n\n장점: 가치판단(ε) 명시적\n단점: ε 선택의 주관성\n로렌츠 교차 시에도 순위 결정 가능","difficulty":2},
    {"number":33,"topicId":"social_insurance","keywords":["건강보험","도덕적해이","역선택","본인부담","공보험"],"coreStatement":"건강보험: 역선택(강제가입으로 해결)+도덕적해이(본인부담금으로 억제). 크림스키밍 방지 위해 공적보험 필요.","answer":1,"basicExplanation":"역선택: 고위험자 집중→보험료↑→저위험자 이탈. 도덕적해이: 보험가입→과잉이용. 본인부담금, 사전심사로 통제.","detailedExplanation":"【보험시장 실패와 공적보험】\n역선택: 정보비대칭→고위험자 집중\n→보험료↑→저위험자 이탈→시장 실패\n해결: 강제가입(공적보험)\n\n도덕적해이: 보험→비용의식↓→과잉이용\n해결: 본인부담(co-payment), 사전심사\n\n크림스키밍: 민간보험이 저위험자만 선별\n→고위험자 공적보험에 집중→재정 불안\n→공적보험의 보편적 적용 필요","difficulty":2},
    {"number":34,"topicId":"public_expenditure","keywords":["예산제도","성과주의","PPBS","ZBB","품목별"],"coreStatement":"품목별: 투입통제. 성과주의: 산출·원가. PPBS: 기획·프로그래밍·예산 연계. ZBB: 매년 영기준에서 검토.","answer":3,"basicExplanation":"발전순서: 품목별(1920s)→성과주의(1950s)→PPBS(1960s)→ZBB(1970s)→신성과주의(1990s). 각각 통제→관리→기획→재검토→성과.","detailedExplanation":"【예산제도 발전】\n품목별(LIBS): 지출항목별→통제 기능, 유사사업 중복 가능\n성과주의(PBS): 업무·원가→관리 기능\nPPBS: 목표→프로그램→예산→기획 기능\nZBB: 모든 사업 영기준→기존 관성 탈피, but 시간↑\nNPB: 산출+성과+재량→신공공관리\n\n우리나라: 성과관리제도+프로그램예산체계 혼용","difficulty":1},
    {"number":35,"topicId":"public_expenditure","keywords":["비용편익분석","NPV","IRR","할인율","사회적할인율"],"coreStatement":"NPV>0이면 사업타당. IRR>사회적할인율이면 타당. 할인율↑→장기사업불리. NPV법이 IRR법보다 이론적 우월.","answer":2,"basicExplanation":"NPV=Σ(B-C)/(1+r)^t. IRR: NPV=0 되는 r. 규모 다른 사업→NPV법 우선. 사회적할인율: 시간선호+기회비용 가중.","detailedExplanation":"【비용편익분석 기준 비교】\nNPV법: NPV>0→채택, 크기로 우선순위\nIRR법: IRR>r→채택\nB/C법: B/C>1→채택\n\nNPV vs IRR 불일치:\n규모 차이, 편익 시점 차이 시\nNPV법: 가치가산 가능→이론적 우월\n\n할인율↑: 미래편익 할인 크게→장기사업↓\n사회적할인율: 시장이자율과 다를 수 있음\n(세금, 외부성, 세대간 형평)","difficulty":2},
    {"number":36,"topicId":"social_insurance","keywords":["근로장려세제","EITC","점증구간","점감구간","노동공급"],"coreStatement":"EITC 점증구간: 실질임금↑효과→노동↑(대체) vs 소득↑→노동↓(소득). 평탄구간: 소득효과만→노동↓. 점감구간: 양효과 모두 노동↓.","answer":4,"basicExplanation":"점증: 근로→장려금↑→대체+소득 반대방향. 평탄: 장려금 일정→소득효과만(노동↓). 점감: 장려금↓→암묵적세금→대체+소득 모두 노동↓.","detailedExplanation":"【EITC 구간별 노동공급 효과】\n점증구간(phase-in):\n  대체효과: 실질임금↑→여가↓→노동↑\n  소득효과: 소득↑→여가↑→노동↓\n  순효과: 불확실(but 비참여자→참여 유인)\n\n평탄구간(plateau):\n  대체효과 없음(암묵세율=0)\n  소득효과만: 노동↓\n\n점감구간(phase-out):\n  대체효과: 실질임금↓→노동↓\n  소득효과: 소득↑→노동↓\n  양 효과 모두 노동↓","difficulty":2},
    {"number":37,"topicId":"macro_is_lm","keywords":["먼델-플레밍","개방경제","고정환율","변동환율","자본이동"],"coreStatement":"변동환율+자본완전이동: 재정무효(환율절상→순수출↓), 통화유효. 고정환율+자본완전이동: 재정유효, 통화무효.","answer":1,"basicExplanation":"먼델-플레밍(IS-LM-BP 모형): 소규모개방경제. 변동환율: 통화정책 유효. 고정환율: 재정정책 유효. 자본이동성이 핵심.","detailedExplanation":"【먼델-플레밍 모형】\n변동환율+완전자본이동:\n재정확대→r↑→자본유입→환율절상→NX↓→Y불변(완전구축)\n통화확대→r↓→자본유출→환율절하→NX↑→Y↑\n\n고정환율+완전자본이동:\n재정확대→r↑→자본유입→외환매입→M↑→LM우이동→Y↑↑\n통화확대→r↓→자본유출→외환매각→M↓→LM원위치→무효\n\n불가능한 삼위일체: 자본이동+고정환율+독립적통화정책 동시 불가","difficulty":3},
    {"number":38,"topicId":"macro_national_income","keywords":["경제성장","솔로우모형","정상상태","기술진보","수렴가설"],"coreStatement":"솔로우 모형: 정상상태에서 1인당 성장=기술진보율. 저축률↑→정상상태 자본↑이나 성장률 불변. 수렴가설.","answer":3,"basicExplanation":"sf(k)=(n+δ)k에서 정상상태 k*. 저축률↑→k*↑(수준↑, 성장률 불변). 기술진보→지속성장. 조건부 수렴: 같은 구조→수렴.","detailedExplanation":"【솔로우 성장모형】\nΔk = sf(k) - (n+δ)k\n정상상태: sf(k*) = (n+δ)k*\n\n저축률↑: k*↑, y*↑ (수준효과)\n인구성장률↑: k*↓, y*↓\n기술진보(A): y/A 정상상태, y는 g_A율로 성장\n\n황금률: f'(k_G) = n+δ (소비 극대화 조건)\n수렴가설: 후진국이 더 빠른 성장→격차 축소\n조건부 수렴: 같은 구조적 조건 하에서 수렴","difficulty":2},
    {"number":39,"topicId":"public_expenditure","keywords":["정부지출","바그너법칙","전위효과","보몰비용병","리바이어던"],"coreStatement":"바그너: 소득↑→정부지출비중↑. 피콕-와이즈만: 전쟁→조세허용↑→톱니효과. 보몰: 정부서비스 생산성↓→상대비용↑.","answer":4,"basicExplanation":"정부지출 팽창: 바그너(수요측), 보몰(비용측), 피콕-와이즈만(충격), 재정착각(인식오류), 리바이어던(정부이기심).","detailedExplanation":"【정부지출 팽창이론 정리】\n바그너법칙: 소득탄력성>1, 공공재는 소득과 비례 이상 증가\n피콕-와이즈만: 전위(displacement)+검사+집중 효과, 톱니(ratchet)\n보몰 비용병: 정부부문 생산성↓→상대비용↑→지출비중↑\n재정착각: 조세부담 과소인식→공공서비스 과다 수요\n리바이어던(뷰캐넌): 정부=세입극대화→과도한 정부 팽창","difficulty":2},
    {"number":40,"topicId":"social_insurance","keywords":["국민연금","수정적립","소득대체율","보험료율","세대간형평"],"coreStatement":"한국 국민연금: 수정적립방식. 저부담-고급여 구조→재정 불안. 소득대체율 하향+보험료율 상향 논의.","answer":2,"basicExplanation":"한국: 보험료율 9%, 소득대체율 40%(하향 추세). 인구고령화→부양비↑→재정고갈 우려→모수적·구조적 개혁 논의.","detailedExplanation":"【한국 국민연금 현황】\n방식: 수정적립(부분적립, 실질 부과방식 이행)\n보험료: 소득의 9%(사용자+근로자 각 4.5%)\n소득대체율: 40%(2028년까지 하향)\n\n문제:\n①저부담-고급여→기금고갈 전망\n②인구고령화→부양비 급증\n③세대간 형평 문제\n\n개혁방향:\n모수개혁: 보험료↑, 소득대체율↓, 수급연령↑\n구조개혁: 다층체계(기초+소득비례+개인)","difficulty":2}
]

parsed = json.loads(Path('d:/Coding/semusa/web/data/parsed/parsed_2024_재정학.json').read_text(encoding='utf-8'))
parsed_map = {q['number']: q for q in parsed['questions']}
all_q = []
for eq in ENRICHMENT:
    orig = parsed_map.get(eq['number'], {})
    all_q.append({**orig, **eq})
all_q.sort(key=lambda x: x['number'])
result = {'year': 2024, 'subject': '재정학', 'totalQuestions': len(all_q), 'questions': all_q}
out = Path('d:/Coding/semusa/web/data/enriched/enriched_2024_재정학.json')
out.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding='utf-8')
print(f'OK {len(all_q)} questions -> {out}')
